---
sudo: required

env:
  - distribution: ubuntu
    version: bionic

services:
  - docker

before_install:
  - 'sudo ./development/1_create.sh ${distribution} ${version}'

script:
  - container_id=$(mktemp)
  - 'sudo ./development/2_run.sh ${distribution} ${version} ${container_id}'
  - 'sudo docker exec "$(cat ${container_id})" /tmp/hostcontrold/development/4_test.sh'
  - 'sudo ./development/5_remove.sh ${container_id}'
