---
sudo: required

env:
  - compiler: gcc
    version: 7
  - compiler: gcc
    version: 8
  - compiler: gcc
    version: 9
  - compiler: gcc
    version: 10
  - compiler: clang
    version: 7
  - compiler: clang
    version: 8
  - compiler: clang
    version: 9
  - compiler: clang
    version: 10

services:
  - docker

install:
  - 'sudo ./development/1_create.sh ${compiler} ${version}'
  - 'export container_id=$(mktemp)'
  - 'sudo ./development/2_run.sh ${compiler} ${version} ${container_id}'

script:
  - 'sudo docker exec "$(cat ${container_id})" /home/hostcontrold/development/4_test.sh'

after_script:
  - 'sudo ./development/5_remove.sh ${container_id}'
