#!/bin/sh

### BEGIN INIT INFO
# Provides:          shutdowndaemon
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:      
# Should-Stop:       
# Short-Description: start shutdowndaemon
### END INIT INFO

NAME=shutdowndaemon
DAEMON=/usr/sbin/shutdowndaemon
PIDDIR=/var/run/shutdowndaemon
PID=$PIDDIR/shutdowndaemon.pid

# clear conflicting settings from the environment
unset TMPDIR

. /lib/lsb/init-functions

case "$1" in
	start)
		# Make sure we have our PIDDIR, even if it's on a tmpfs
		install -o root -g root -m 755 -d $PIDDIR

		# start daemon
		log_daemon_msg "Starting the process" "$NAME"
		start-stop-daemon --start --quiet --oknodo --pidfile $PID --make-pidfile --background --exec $DAEMON
		log_end_msg 0
		
		;;
		
	stop)
		log_daemon_msg "Stoping the process" "$NAME"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $PID ] && ! ps h `cat $PID` > /dev/null
		then
			# Stale PID file (daemon was succesfully stopped),
			# remove it
			rm -f $PID
		fi
		log_end_msg 0
		
		;;

	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
		
    status)
		if [ -e $PID ]; then
			status_of_proc -p $PID $DAEMON "$NAME process" && exit 0 || exit $?
		else
			log_daemon_msg "$NAME Process is not running"
			log_end_msg 0
		fi
		;;
		
	*)
		echo "Usage: /etc/init.d/shutdowndaemon {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
