name: software_build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        version: [7, 8, 9, 10]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: System information
        run: |
          uname -a
          lsb_release -a
          sudo docker --version

      - name: Prepare and run container
        run: |
          sudo ./development/1_create.sh ${{matrix.compiler}} ${{matrix.version}}
          sudo ./development/2_run.sh ${{matrix.compiler}} ${{matrix.version}}

      - name: Test
        run: |
          sudo docker exec test-container ${{matrix.compiler}} --version
          sudo docker exec test-container /home/hostcontrold/development/4_test.sh

      - name: Cleanup
        run: |
          sudo ./development/5_remove.sh
